# Generated by Django 3.1.7 on 2021-07-04 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GlobalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='a_comme_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('son_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('util_connecte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GlobalApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connecte_a_contact', models.BooleanField(default=True, null=True)),
                ('msg', models.TextField(max_length=5000)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.a_comme_contact')),
            ],
        ),
        migrations.CreateModel(
            name='est_membre_de',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GlobalApp.room')),
                ('pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GlobalApp.patient')),
            ],
        ),
    ]
